spring:
  application:
    name: hotel-search-tracking-service
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  datasource:
    url: ${ORACLE_JDBC_URL}
    username: ${ORACLE_APP_USER}
    password: ${ORACLE_APP_PASSWORD}
    hikari:
      maximum-pool-size: 12
      minimum-idle: 4
  flyway:
    sql-migration-suffixes:
      - .sql
      - .pks
      - .pkb
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        linger.ms: 2
        batch.size: 65536
        compression.type: lz4
        buffer.memory: 67108864
    consumer:
      group-id: hotel-search-persistence
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 250
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.value.default.type: com.riu.hotelsearch.infrastructure.messaging.kafka.SearchEventMessage
        spring.json.trusted.packages: com.riu.hotelsearch.infrastructure.adapter.out.kafka
    listener:
      ack-mode: batch
      type: batch
      concurrency: 6

server:
  tomcat:
    accept-count: 1000

app:
  kafka:
    topic: ${KAFKA_TOPIC:hotel_availability_searches}
    partitions: 6
